Shade okhttp in kamon-datadog
kamon-io/Kamon pull request #1069
Opened 2021-10-29 14:03 UTC by seglo

Hi. I don't know if there's an appetite to shade arbitrary libraries in Kamon instrumentations like this, but it would be really helpful since the okhttp dependency is rather ubiquitous in other libraries (at least the libs I use).

BTW, the link to the "spray commit guidelines" is broken and I'm not sure if it's hosted somewhere else.

https://github.com/kamon-io/Kamon/blob/master/CONTRIBUTING.md?plain=1#L34

2021-11-02 15:37 UTC, ivantopo requested changes
I'm totally fine with this, just need that tiny change in the build and we are good to go.

2021-11-02 15:37 UTC, ivantopo commented on build.sbt
> +    `kamon-datadog` % "shaded",
Hey @seglo, please remove this one line and I think we should be ready to go.

2021-11-04 15:44 UTC, seglo commented on build.sbt
> +    `kamon-datadog` % "shaded",
Terrific. Thanks @ivantopo! I made the change.

2021-11-05 10:59 UTC, merged

2021-11-05 11:00 UTC, ivantopo commented
Thanks a lot @seglo!