kamon-prometheus: Add default buckets for Dimension.Percentage
kamon-io/Kamon pull request #1266
Opened 2023-03-15 18:41 UTC by jatcwang

2023-03-29 19:23 UTC, ivantopo requested changes
Hey @jatcwang thanks for working on this!

There is a compilation issue on the tests, please see here: https://github.com/kamon-io/Kamon/actions/runs/4429816623/jobs/8037791330#step:6:18336

Other than that it looks good to me.

2023-03-29 19:23 UTC, ivantopo commented on reporters/kamon-prometheus/src/main/resources/reference.conf
> +    percentage-buckets = [
It saddens me that there is such a wide spread across those buckets but well, that's how it has to be :shrug:

2023-03-30 16:13 UTC, jatcwang commented
@ivantopo Thanks for the review. Can you tell me what's wrong with the latest test failure? Seems like a flaky test and unrelated to my changes? https://github.com/kamon-io/Kamon/actions/runs/4566168676/jobs/8058292358?pr=1266#step:6:4421

2023-04-04 13:59 UTC, ivantopo commented
@jatcwang just a random test failure, I'm re-running the tests now but as long as this compiles we should be good to go :smile:

2023-04-04 14:27 UTC, ivantopo approved these changes

2023-04-04 14:28 UTC, merged